// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/kujilabo/cocotola-tatoeba-api/src/app/service"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// TatoebaLinkRepository is an autogenerated mock type for the TatoebaLinkRepository type
type TatoebaLinkRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, param
func (_m *TatoebaLinkRepository) Add(ctx context.Context, param service.TatoebaLinkAddParameter) error {
	ret := _m.Called(ctx, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.TatoebaLinkAddParameter) error); ok {
		r0 = rf(ctx, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTatoebaLinkRepository creates a new instance of TatoebaLinkRepository. It also registers a cleanup function to assert the mocks expectations.
func NewTatoebaLinkRepository(t testing.TB) *TatoebaLinkRepository {
	mock := &TatoebaLinkRepository{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
