// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// TatoebaLinkAddParameter is an autogenerated mock type for the TatoebaLinkAddParameter type
type TatoebaLinkAddParameter struct {
	mock.Mock
}

// GetFrom provides a mock function with given fields:
func (_m *TatoebaLinkAddParameter) GetFrom() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetTo provides a mock function with given fields:
func (_m *TatoebaLinkAddParameter) GetTo() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewTatoebaLinkAddParameter creates a new instance of TatoebaLinkAddParameter. It also registers a cleanup function to assert the mocks expectations.
func NewTatoebaLinkAddParameter(t testing.TB) *TatoebaLinkAddParameter {
	mock := &TatoebaLinkAddParameter{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
