// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/kujilabo/cocotola-tatoeba-api/pkg/service"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// TatoebaLinkAddParameterIterator is an autogenerated mock type for the TatoebaLinkAddParameterIterator type
type TatoebaLinkAddParameterIterator struct {
	mock.Mock
}

// Next provides a mock function with given fields: ctx
func (_m *TatoebaLinkAddParameterIterator) Next(ctx context.Context) (service.TatoebaLinkAddParameter, error) {
	ret := _m.Called(ctx)

	var r0 service.TatoebaLinkAddParameter
	if rf, ok := ret.Get(0).(func(context.Context) service.TatoebaLinkAddParameter); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.TatoebaLinkAddParameter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTatoebaLinkAddParameterIterator creates a new instance of TatoebaLinkAddParameterIterator. It also registers a cleanup function to assert the mocks expectations.
func NewTatoebaLinkAddParameterIterator(t testing.TB) *TatoebaLinkAddParameterIterator {
	mock := &TatoebaLinkAddParameterIterator{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
